name: Services

# Add "id-token" with the intended permissions. See https://github.com/google-github-actions/auth?tab=readme-ov-file#usage
permissions:
  contents: 'read'
  id-token: 'write'

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.5.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20.15.1
      - id: auth
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
      - run: pnpm install
      - run: pnpm test

      # - run: pnpm start 
